-- 创建评论表
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  avatar TEXT DEFAULT '',
  text TEXT NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 启用行级安全策略
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 允许所有人读取评论
CREATE POLICY "Public comments are viewable by everyone."
  ON comments FOR SELECT
  USING (true);

-- 允许所有人插入评论
CREATE POLICY "Users can insert comments."
  ON comments FOR INSERT
  WITH CHECK (true);